version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: crm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dta:/var/lib/postgres/data
    networks:
      - crm_network
    restart: unless-stopped
