@baseUrl = http://localhost:3333
@id = b4809346-1fe6-43a2-bf58-1471174463d1

# Account Route

# @name createAccount

POST {{baseUrl}}/account HTTP/1.1
Content-Type: application/json

{
  "email": "victor222@conective.com",
  "maxClients": 10,
  "maxProjects": 2,
  "name": "Victor",
  "password": "1234567890",
  "plan": "FREE"
}


### 

# GET account by id

# @name getAccountById

GET {{baseUrl}}/account/{{id}} HTTP/1.1


### 

# PUT - Update account

# @name updateAccount

PUT {{baseUrl}}/account/{{id}} HTTP/1.1
Content-Type: application/json

{
  "email": "victor_updated@conective.com",
  "maxClients": 20,
  "maxProjects": 5,
  "name": "Victor Updated",
  "password": "newpassword123",
  "plan": "BASIC"
}


### 

# PATCH - Update last login

# @name updateLastLogin

PATCH {{baseUrl}}/account/{{id}}/last-login HTTP/1.1


### 

# PATCH - Update password

# @name updatePassword

PATCH {{baseUrl}}/account/{{id}}/password HTTP/1.1
Content-Type: application/json

{
  "password": "mynekjsdfkujdfoi323932883928ifds6"
}


### 

# DELETE - Delete account

# @name deleteAccount

DELETE {{baseUrl}}/account/{{id}} HTTP/1.1
