@accountId = 1b34beb8-2a3e-41e0-b98c-7401128661e7
@baseUrl = http://localhost:3333
@projectId = 1b34beb8-2a3e-41e0-b98c-7401128661e7
@taskId = 73b6b58d-b4a3-4e3c-a9db-e22ea24c6500
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliNzBjMmJjLWZkMTMtNDZlNS04NjY1LWFhOTNkMjQwNTkyOSIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwiaWF0IjoxNzYyMTc5MTg0LCJleHAiOjE3NjI3ODM5ODR9.v0AqjO74zA8YlH3ZnM2Si39SjhAzv2HWRs8BTNV25z0


### 

# POST - Create Project

# @name createProject

POST {{baseUrl}}/project HTTP/1.1
Cookie: token={{token}}
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "description": "Projeto para gerenciar tarefas e projetos da equipe",
  "title": "Sistema de Gerenciamento de Tarefas"
}


### 

# GET - Get Project by ID

# @name getProjectById

GET {{baseUrl}}/project/{{projectId}} HTTP/1.1
Cookie: token={{token}}


### 

# GET - Get Projects by AccountID

# @name getProjectsAccountId

GET {{baseUrl}}/projects/{{accountId}} HTTP/1.1
Cookie: token={{token}}


### 

# PUT - Update Project

# @name updateProject

PUT {{baseUrl}}/project/{{projectId}} HTTP/1.1
Content-Type: application/json
Cookie: token={{token}}

{
  "description": "Projeto completo para gerenciar tarefas, projetos e equipes",
  "title": "Sistema de Gerenciamento de Tarefas - Atualizado"
}


### 

# DELETE - Delete Project

# @name deleteProject

DELETE {{baseUrl}}/project/{{projectId}} HTTP/1.1
Cookie: token={{token}}
