@accountId = dd3501e0-3b73-4d60-b617-ee0abc3f1afa
@baseUrl = http://localhost:3333
@projectId = 2ee929c0-c911-462b-bdb5-3a23af80c6d8
@taskId = 4418c706-7d20-4b44-96e0-8304c708e3c4


### 

# POST - Create Project

# @name createProject

POST {{baseUrl}}/project HTTP/1.1
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "description": "Projeto para gerenciar tarefas e projetos da equipe",
  "title": "Sistema de Gerenciamento de Tarefas"
}


### 

# GET - Get Project by ID

# @name getProjectById

GET {{baseUrl}}/project/{{projectId}} HTTP/1.1


### 

# PUT - Update Project

# @name updateProject

PUT {{baseUrl}}/project/{{projectId}} HTTP/1.1
Content-Type: application/json

{
  "description": "Projeto completo para gerenciar tarefas, projetos e equipes",
  "title": "Sistema de Gerenciamento de Tarefas - Atualizado"
}


### 

# DELETE - Delete Project

# @name deleteProject

DELETE {{baseUrl}}/project/{{projectId}} HTTP/1.1
