@baseUrl = http://localhost:3333
@projectId = 33300fa4-2f79-480b-9767-5cd21a75dced
@taskId = 32f7c7fe-c1be-4afb-8987-67c73db2cadb
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliNzBjMmJjLWZkMTMtNDZlNS04NjY1LWFhOTNkMjQwNTkyOSIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwiaWF0IjoxNzYyMTc5MTg0LCJleHAiOjE3NjI3ODM5ODR9.v0AqjO74zA8YlH3ZnM2Si39SjhAzv2HWRs8BTNV25z0


### 

# POST - Create Task

# @name createTask

POST {{baseUrl}}/task HTTP/1.1
Content-Type: application/json
Cookie: token={{token}}

{
  "description": "Criar sistema de login e registro de usuários",
  "priority": "HIGH",
  "projectId": "{{projectId}}",
  "status": "TODO",
  "title": "Implementar autenticação"
}


### 

# GET - Get Task by ID

# @name getTaskById

GET {{baseUrl}}/task/{{taskId}} HTTP/1.1
Cookie: token={{token}}


### 

# GET - Get All Tasks by Project

# @name getAllTasks

GET {{baseUrl}}/project/tasks/{{projectId}} HTTP/1.1
Cookie: token={{token}}


### 

# PUT - Update Task

# @name updateTask

PUT {{baseUrl}}/task/{{taskId}} HTTP/1.1
Content-Type: application/json
Cookie: token={{token}}

{
  "description": "Criar sistema de login e registro com JWT tokens",
  "priority": "HIGH",
  "status": "DOING",
  "title": "Implementar autenticação JWT"
}


### 

# DELETE - Delete Task

# @name deleteTask

DELETE {{baseUrl}}/task/{{taskId}} HTTP/1.1
Cookie: token={{token}}
